### ISSUE TITLE
Remove console logs

### ISSUE THREAD

**Issue by adamreisnz** [volumetric/Bring-Google-View-Image-Back#3]
The console logs from this plugin are polluting the browser console in every page that I visit, which is distracting when doing development debugging.

Can you please remove and clean up all console statements from the code and only run these when you are testing/debugging?

Other than that great plugin, I don't know what Google was thinking.

**Comment by vinit-agr** [comment]
Pushed an update to remove the logs.
https://github.com/volumetric/Bring-Google-View-Image-Back/commit/b11a872257520c9bd0304456773c40376e3d2fcc
